### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [cppan/cppan#27] opened 2017-07-13 17:46 UTC
Hi, when I try to configure the [Qt example](https://github.com/cppan/tests/blob/master/tests/ok/qt.widgets.cpp), CMake gives me the following errors:

```
-- Building for: Visual Studio 15 2017
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:404 (get_configuration)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:404 (get_configuration)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:404 (get_configuration)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:404 (get_configuration)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:404 (get_configuration)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:405 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:405 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:405 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:405 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:405 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:99 (get_configuration_variables)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  .cppan/helpers.cmake:67 (get_configuration)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  .cppan/helpers.cmake:67 (get_configuration)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  .cppan/helpers.cmake:67 (get_configuration)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  .cppan/helpers.cmake:67 (get_configuration)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:374 (get_configuration_unhashed)
  .cppan/helpers.cmake:67 (get_configuration)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  .cppan/helpers.cmake:68 (get_configuration_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  .cppan/helpers.cmake:68 (get_configuration_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  .cppan/helpers.cmake:68 (get_configuration_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  .cppan/helpers.cmake:68 (get_configuration_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  .cppan/helpers.cmake:68 (get_configuration_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  .cppan/helpers.cmake:69 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  .cppan/helpers.cmake:69 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  .cppan/helpers.cmake:69 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  .cppan/helpers.cmake:69 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:384 (get_configuration_with_generator_unhashed)
  .cppan/helpers.cmake:69 (get_configuration_with_generator)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:243 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  .cppan/helpers.cmake:70 (get_configuration_with_generator_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:244 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  .cppan/helpers.cmake:70 (get_configuration_with_generator_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:245 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  .cppan/helpers.cmake:70 (get_configuration_with_generator_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:246 (find_flag):
  find_flag Function invoked with incorrect arguments for function named:
  find_flag
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  .cppan/helpers.cmake:70 (get_configuration_with_generator_unhashed)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:288 (prepare_config_part):
  prepare_config_part Function invoked with incorrect arguments for function
  named: prepare_config_part
Call Stack (most recent call first):
  C:/Users/xxxx/.cppan/storage/etc/static/functions.cmake:317 (get_configuration_unhashed)
  .cppan/helpers.cmake:70 (get_configuration_with_generator_unhashed)
  .cppan/CMakeLists.txt:101 (include)


-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckIncludeFile.cmake:56 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:223 (check_include_file)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:24 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Looking for sys/types.h - not found
-- Looking for stdint.h
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckIncludeFile.cmake:56 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:224 (check_include_file)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:24 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Looking for stdint.h - not found
-- Looking for stddef.h
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckIncludeFile.cmake:56 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:225 (check_include_file)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:24 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Looking for stddef.h - not found
-- Check size of unsigned short
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:114 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:239 (__check_type_size_impl)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:24 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Check size of unsigned int
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:114 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_INT.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:239 (__check_type_size_impl)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:29 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Check size of unsigned long
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:114 (try_compile):
  Unknown extension ".c" for file

    C:/Tests/cppan/qt/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_LONG.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX RC

  See project() command to enable other languages.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/CheckTypeSize.cmake:239 (__check_type_size_impl)
  C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:36 (CHECK_TYPE_SIZE)
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/TestBigEndian.cmake:41 (message):
  no suitable type found
Call Stack (most recent call first):
  .cppan/helpers.cmake:123 (test_big_endian)
  .cppan/CMakeLists.txt:101 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Tests/cppan/qt/build/CMakeFiles/CMakeOutput.log".
See also "C:/Tests/cppan/qt/build/CMakeFiles/CMakeError.log".
```

I'm using Visual Studio 2017 (Community), CMake 3.8 and cppan built from master.

Thanks.

**Comment by egorpugin** [comment] 2017-07-14 01:42
What is your configure command?

**Comment by usernameiwantedwasalreadytaken** [comment] 2017-07-14 11:21
Just `cmake ..` (inside the build directory).

**Comment by egorpugin** [comment] 2017-07-14 12:22
Confirmed, thanks. Working on it.

**Comment by egorpugin** [comment] 2017-07-14 15:04
Ok, should be fixed now. Please, test it.
Rebuild cppan or use `cppan --self-upgrade` or dl from website.
Also replace bottom of your `CMakeLists.txt` file with
```
add_executable(main src/main.cpp)
target_link_libraries(main
    pvt.cppan.demo.qtproject.qt.base.widgets
    pvt.cppan.demo.qtproject.qt.base.winmain
    pvt.cppan.demo.qtproject.qt.base.plugins.platforms.windows
)
```

Linking `cppan` target is disabled some time ago. Now you must explicitly specify deps.

**Comment by usernameiwantedwasalreadytaken** [comment] 2017-07-17 14:10
Thanks!

But I still could not build it...

I tried with GCC + Ninja and got:

```
ninja: error: 'C:/Users/xxxx/.cppan/storage/lib/d2d0f2b8/Release/libpvt.cppan.demo.qtproject.qt.base.widgets-5.9.1.dll.a', needed by 'main.exe', missing and no known rule to make it
```

Then I tried with Visual Studio 2017 and got

```
1>Error copying file (if different) from "C:/Users/xxxx/.cppan/storage/bin/cf2da322/Debug/pvt.cppan.demo.qtproject.qt.base.plugins.platforms.windows-5.9.1.dll" to "C:/Tests/cppan/qt/build_vs/Debug/plugins/platforms/pvt.cppan.demo.qtproject.qt.base.plugins.platforms.windows-5.9.1.dll".
```

(there is no such file `C:/Users/xxxx/.cppan/storage/bin/cf2da322/Debug/pvt.cppan.demo.qtproject.qt.base.plugins.platforms.windows-5.9.1.dll`)

**Comment by egorpugin** [comment] 2017-07-17 14:31
Can you try to remove storage dir completely and run again?

**Comment by egorpugin** [comment] 2017-07-17 15:26
By the way, I see errors with ninja also.
Ninja support is really not in the best shape, so issues can be seen.
Checking now VS build...

**Comment by egorpugin** [comment] 2017-07-17 19:04
VS works for me and I found a way where ninja works too.
Set you `cppan.yml` to
```
local_settings:
    dependencies:
        - pvt.cppan.demo.qtproject.qt.base.widgets: 5
        - pvt.cppan.demo.qtproject.qt.base.winmain: 5
        - pvt.cppan.demo.qtproject.qt.base.plugins.platforms.windows: 5
```

In `CMakeLists.txt` set `project(simple)` without any languages.
Then run `vcvars*.bat` or open VS command line.
Then `mkdir win32_ninja && cd win32_ninja && cppan -d .. && cmake .. -G Ninja && ninja`.

**Comment by egorpugin** [comment] 2017-07-19 21:38
I fixed several ninja issues locally (binaries are not uploaded yet), but was hit by ninja error.
See their ticket https://github.com/ninja-build/ninja/issues/1161

**Comment by egorpugin** [comment] 2017-07-20 10:07
New binaries are uploaded, but ninja has the issue above.

**Comment by usernameiwantedwasalreadytaken** [comment] 2017-07-20 11:36
Ok. Thanks.

**Closed** 2018-03-12 15:36 UTC
